name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9, 3.11, 3.12]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m venv .venv
                source .venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt

            - name: Lint & Test
              run: |
                source .venv/bin/activate
                pytest --maxfail=1 --disable-warnings -q
